apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heads-up
spec:
  rules:
    - host: heads-up.lab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heads-up
                port:
                  number: 80
